name: Deploy VHDPlus Storefront

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          project_id: vhdplus
          credentials_json: ${{ secrets.VHDPLUS_SHOP_GCLOUD_KEY }}
      - uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: vhdplus
      - name: Build Docker container
        run: ./build-docker.sh

  deploy:
    name: Deploying
    needs: [ build ]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          project_id: vhdplus
          credentials_json: ${{ secrets.VHDPLUS_SHOP_GCLOUD_KEY }}
      - uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: vhdplus
      - run: 'echo "$SECRET_VARS" > .env'
        env:
          SECRET_VARS: ${{secrets.ENV_PROD}}
      - run: ./deploy.sh vhdplus-shop-storefront 1G
